### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by se6astian-pi** [apertus-open-source-cinema/cmv12k_color_science#1]
$ python3 analyze.py darkframe_2x_0.990192.blob.zst means
Traceback (most recent call last):
  File "analyze.py", line 49, in <module>
    darkframes = read_darkframes(filename)
  File "/mnt/6816eb16-437e-4d93-8365-84213d4de9ad/recorder/cmv12k_color_science/raw_io.py", line 39, in read_darkframes
    def get_corners(data, width: int, height: int) -> list[CornerMarker]:
TypeError: 'type' object is not subscriptable

**Comment by rroohhh** [comment]
Which python version are you using?

I think this syntax requires 3.9 atleast, but removing the type annotation does not change anything, so thats a option aswell.
